<?php
$TR = array(
	'cs' => array(
		'form' => array(
			'fields' => array(
				'login' => 'Přihlašovací jméno',
				'name' => 'Celé jméno',
				'email' => 'E-mail',
				'birth' => 'Rok narození',
				'address' => 'Ulice, č.p.',
				'zip' => 'PSČ',
				'city' => 'Město',
				'country' => 'Stát',
				'how' => 'Jak ses o nás dozvěděl?',
				'note' => 'Poznámky',
				'distribution' => 'Vyber si distribuci',
				'location' => 'Preferovaná lokace pro VPS',
				'currency' => 'Měna platby členského příspěvku',
				'org_name' => 'Název organizace',
				'ic' => 'IČ',
			),
			'errors' => array(
				'REGFAILED' => 'Registrace se nezdařila',
				'NOTEMPTY' => 'musí být vyplněno',
				'NOTSELECTED' => 'vyber některou z nabízených voleb',
				'LEN_2' => 'musí mít minimálně 2 znaky',
				'LEN_6' => 'musí mít minimálně 6 znaků',
				'NOTNUM' => 'nemůže obsahovat číslo',
				'NUMONLY' => 'může obsahovat pouze číclice 0-9',
				'NOTLOGIN' => 'může obsahovat pouze znaky a-z, A-Z, 0-9, pomlčka a tečka, 2 až 63 znaků',
				'NOTMAIL' => 'není platná e-mailová adresa',
				'EHOTMAIL' => 'omlouváme se, ale mail servery od Microsoftu nedoručují naše maily',
				'NOTBIRTH' => 'nepřijatelný rok narození',
				'NOHOUSEN' => 'chybí číslo popisné',
				'TWODOTS' => 'nesmí obsahovat dvě tečky zasebou',
				'TWOHYPHENS' => 'nesmí obsahovat dvě pomlčky zasebou',
				'EEXISTS' => 'tato hodnota už je použita, zvol prosím jinou',
				'EFAILED' => 'Přihlášku se nepodařilo uložit. Zkus to prosím znovu, případně napiš na podpora@vpsfree.cz.',
			)
		),
	),
	'en' => array(
		'form' => array(
			'fields' => array(
				'login' => 'Login name',
				'name' => 'Name',
				'email' => 'E-mail',
				'birth' => 'Year of birth',
				'address' => 'Street, number',
				'zip' => 'ZIP/Postal code',
				'city' => 'City',
				'country' => 'State',
				'how' => 'How did you learn about us?',
				'note' => 'Notes',
				'distribution' => 'Choose your distro',
				'location' => 'Preferred location for your VPS',
				'currency' => 'Currency for member fees',
				'org_name' => 'Company name',
				'ic' => 'ID',
			),
			'errors' => array(
				'REGFAILED' => 'Registration failed',
				'NOTEMPTY' => 'must be filled',
				'NOTSELECTED' => 'choose one option',
				'LEN_2' => 'must contain at least 2 characters',
				'LEN_6' => 'must contain at least 6 characters',
				'NOTNUM' => 'cannot contain numbers',
				'NUMONLY' => 'can contain only numbers 0-9',
				'NOTLOGIN' => 'can contain only characters a-z, A-Z, 0-9, dash and dot, 2 to 63 chars',
				'NOTMAIL' => 'it is not valid mail address',
				'EHOTMAIL' => 'sorry, but Microsoft mail servers are dropping our mails',
				'NOTBIRTH' => 'unacceptable year of birth',
				'NOHOUSEN' => 'house number is missing',
				'TWODOTS' => 'cannot contain two dots in a row',
				'TWOHYPHENS' => 'cannot contain two dashes in a row',
				'EEXISTS' => 'this value is already used, choose another',
				'EFAILED' => 'We cannot save your registration. Please try again or contact support: podpora@vpsfree.cz.',
			)
		),
	),
);
